site_name: Leiden Cell Observatory Wiki
repo_url: https://github.com/Leiden-Cell-Observatory/Leiden-Cell-Observatory.github.io
edit_uri: edit/main/docs/
repo_name: Leiden-Cell-Observatory.github.io
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - header.autohide
    - announce.dismiss
    - content.code.copy
    - content.code.annotate 
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.follow
    - navigation.footer
    - navigation.expand
    - navigation.prune
    - navigation.collapsible
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - content.action.edit
  logo: logo/LCO_logo.png
  favicon: logo/favicon.ico

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: ''
  - sane_lists
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Leiden-Cell-Observatory
    - icon: material/home
      link: https://www.universiteitleiden.nl/en/science/cell-observatory

extra_css:
  - assets/custom.css

nav:
  - Home: index.md
  - Microscopes:
    - microscopes/index.md
    - IBL Microscopes: microscopes/iblmicroscopes.md
    - LACDR Microscopes: microscopes/lacdrmicroscopes.md
    - LIC Microscopes: microscopes/licmicroscopes.md
  - OMERO:
    - omero/index.md
    - Getting Started: omero/getting-started.md
    - Importing: 
      - Overview: omero/importing.md
      - File formats: omero/importing/microscope-files.md
      - HCS data: omero/importing/hcs-data.md
      - Metadata: omero/importing/metadata.md
      - HCS metadata: omero/importing/mihcsme.md
    - Downloading: omero/downloading.md
    - OMERO.figure: omero/figure-creation.md
  - Image analysis:
    - OMERO: 
      - Fiji: omero/analysis/analysis_fiji.md
      - Python: omero/analysis/analysis_python.md
      - R: omero/analysis/analysis_r.md
      - CellProfiler: omero/analysis/analysis_cellprofiler.md
    - analysis/index.md
    - CellProfiler: analysis/cellprofiler.md
    - Fiji: 
      - analysis/Fiji.md
      - TrackMate: analysis/Trackmate.md
    - QuPath: analysis/qupath.md
    - Ilastik: analysis/ilastik.md
    - GitHub: analysis/github.md
    - Python:
      - Conda: analysis/conda.md
      - napari: analysis/napari.md
      - CellPose: analysis/cellpose.md
      - Micro-SAM: analysis/micro-sam.md
    - Computing:
      - computing/index.md
      - HPC: computing/hpc.md
      - Workstations: computing/workstations.md
  - High-Content Screening:
    - hcs/index.md
    - Standard Protocol: hcs/protocol.md
  - Publishing:
    - publishing/index.md
    - Sharing data: publishing/sharing_data.md
    - Citing Cell Observatory: publishing/citing.md
    - Methods: publishing/methods.md    
  - Training:
    - courses/index.md
    - Activities: courses/activities.md
    - PhD Course: courses/phd-course.md
  - Resources: resources.md
  - Contributing: contributing.md
  - Contact: contact.md

copyright: >
  Â© Copyright 2025 Leiden Cell Observatory, Leiden University.
  All content is licensed under the <a href="https://creativecommons.org/licenses/by/4.0/">
  Creative Commons Attribution 4.0 International License</a>.
