[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "Leiden-Cell-Observatory.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"

[pypi-dependencies]
mkdocs-material = { version = ">=9.7.1, <10", extras = ["imaging"] }
jinja2 = ">=3.1.6, <4"
requests = ">=2.32.5, <3"
dotenv = ">=0.9.9, <0.10"
mkdocs-gen-files = ">=0.6.0, <0.7"
mkdocs-literate-nav = ">=0.6.2, <0.7"
